### ISSUE TITLE
Support physics.

### ISSUE THREAD

**Issue by ContentsViewer** [ContentsViewer/nodec#3]
# Goal
* Simply add the physics module.
* Support hit test (at least 2D).

**Comment by Kusunoki-19** [comment]
> Simply add the physics module

Is that mean add some physics API sets of wrapping bullet3 modules?

like under

/modules
  /include  <-- module headers as nodec
  /src <-- cpp souces (or some bullet3 code?)
  /unit_test
    ... / main.cpp <-- for test

**Comment by ContentsViewer** [comment]
@Kusunoki-19 

>> Simply add the physics module
> 
> Is that mean add some physics API sets of wrapping bullet3 modules?

Yes, that's right.

However, the physics engine is dependent on the platform, so the bullet should be in the `platforms/sdks`.

The project source tree will be like below.

```
/modules
    /nodec_physics
        /docs <-- some documents.
        /include  <-- module headers
            /nodec_physics <-- The header files of nodec_physics will be placed in it.
                /components <-- The component structs will be placed in it. 
        /src <-- cpp souces, if any. 
        /tests
             /CMakeLists.txt
             ... /main.cpp <-- for test
/platforms
    /sdks
        /bullet
            / bullet3 <-- submodule
    /projects
        /game_engine
            /tests
                /physics <- The test directory for the module `nodec_physics` with bullet3.
``` 

What do you think?

**Comment by ContentsViewer** [comment]
@Kusunoki-19
Hi.
I'm now going to develop `nodec_physics`.
Please push the materials you have developped to `feature/physics` branch if any.

**Comment by Kusunoki-19** [comment]
I'm sorry. I have nothing to merge because I have not been able to do any development, only study.
